### ISSUE TITLE
border的一些小发现

### ISSUE THREAD

**Issue by MHeroBrine** [MHeroBrine/blog#4]
## border的一些小发现

在学习css绘制图形的时候发现了一些border的特性，首先问题是：如何用纯css画一个三角形

```html
<div class="box"></div>
```
```css
.box {
    width: 0;
    height: 0;
    border-top: 20px solid #000;
    border-right: 18px solid transparent;
    border-left: 18px solid transparent;
}
注：transparent表示透明
```

![](https://github.com/MHeroBrine/blog/raw/master/image/border_1.png)

这个设置方法非常的诡异，这个盒子既没有高和宽，单纯对border进行设置，却可以设置出三角形的效果，起初对着这段代码想了一会儿也没想出来，所以我进行了几个小实验

```html
<div class="box"></div>
```
```css
.box {
    width: 50px;
    height: 50px;
    background-color: #00ffff;
}
```

先创建一个如图所示的盒子

![](https://github.com/MHeroBrine/blog/raw/master/image/border_2.png)

然后，我们给它设置一个border-top，为了看得更清楚，我设置的长度更大一点

```css
.box {
    width: 50px;
    height: 50px;
    background-color: #00ffff;
    border-top: 20px solid #000;
}
```

![](https://github.com/MHeroBrine/blog/raw/master/image/border_3.png)

如我们所见，出现了一个超级厚的border-top，接着再为其设置一个border-right

但是再设置之前请思考一个问题，设置出来的border-right的面积，会不会将border-top拓宽出来的部分也覆盖到？

是左，还是右？

![](https://github.com/MHeroBrine/blog/raw/master/image/border_4.jpg)

```css
.box {
    width: 50px;
    height: 50px;
    background-color: #00ffff;
    border-top: 20px solid #000;
    border-right: 10px solid #000;
}
```

![](https://github.com/MHeroBrine/blog/raw/master/image/border_5.png)

看起来是会包含，接着，我们依次为bottom和left也设置边距

```css
.box {
    width: 50px;
    height: 50px;
    background-color: #00ffff;
    border-top: 20px solid #000;
    border-right: 10px solid #000;
    border-bottom: 20px solid #000;
    border-left: 10px solid #000;
}
```

![](https://github.com/MHeroBrine/blog/raw/master/image/border_6.png)

最后，我们将border-right的颜色改变一下，看看会发生什么
```css
border-right: 10px solid #008000;
```

![](https://github.com/MHeroBrine/blog/raw/master/image/border_8.png)

想不到吧，平时只有1px,2px的border在单独设置颜色时，确实很难注意到边角的颜色变化，但是一旦他们被放大，这种情况就会非常明显，这时我们就需要研究一下border区域的面积范围

我总结了一下它们的规律，这里就直接放一张图来解释，以border-right为样本

![](https://github.com/MHeroBrine/blog/raw/master/image/border_9.jpg)

再回到最开始的三角形的border-right，因为没有height，所以没有上底，因为有border-top，所以有下底，高即是border-right的长度，所以就是一个三角形的面积（即半个大三角形），左边border-left也是同理
